### ISSUE TITLE
Good Efforts and small Changes 

### ISSUE THREAD

**Issue by aswinkumar1999** [prateekagrawalgithub/Electronics-club-Mini-Task-1#1]
Hey , I've gone through multiple repositories of those projects and saw your progress , I would like you to add Hyperlinks in the `Mini-Task-1` --> ` README.MD` file. 

[Kindly Take a Look at this for an example](https://github.com/Ruban-VP/Electronics-club-mini-task-1)

[References](https://guides.github.com/features/mastering-markdown/)

**Comment by iamprateekagrawal** [comment]
Thanks for the review! I have made the changes. 
Additionally, I will try to bring all 25 repositories of each project under `Mini-Task-1` repository.
